FROM node:19.8.1 as build

WORKDIR /app

COPY package*.json .

RUN yarn install

COPY . .

RUN yarn run build

FROM nginx

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

COPY --from=dist /app/build/usr/share/nginx/html .